keyboard: nanosic_driver_v2: Fix missing type specifier in xiaomi_keyboard_init
This fixes following error:
In file included from ../drivers/input/keyboard/nanosic_driver_v2/nano_chardev.c:33:
../drivers/input/keyboard/nanosic_driver_v2/nano_macro.h:285:32: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
  285 | __attribute__((unused)) static xiaomi_keyboard_init(struct nano_i2c_client* i2c_client);
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
      | int
1 error generated.

Change-Id: I017f63ea84671123b408fb8691cc332073a5ad49
Signed-off-by: UtsavBalar1231 <utsavbalar1231@gmail.com>